# Generated by Django 3.1.2 on 2020-10-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
    ]
